Repository wecode-bootcamp-korea/40-1st-CodeSecurityGuard-frontend, pull requests merged in 2022-12, with the labels that each got.

#8 [40기 신창훈] Modify: Footer 기초문법에 맞게 수정완료
  public/images/1.jpg
  public/images/ad1.png
  public/images/carticonimage.jpg
  src/Router.js
  src/pages/Footer/Footer.js
  src/pages/Footer/Footer.scss
  src/pages/ProductList/Product/ProductCard.js
  src/pages/ProductList/Product/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#5 [40기 신창훈] ADD: ProductCard Component 기본틀
  public/images/1.jpg
  public/images/carticonimage.jpg
  src/Router.js
  src/pages/ProductList/Product/ProductCard.js
  src/pages/ProductList/Product/ProductCard.scss
Labels: 추가 기능 구현 중

#2 [40기 윤수인] Signin 페이지 레이아웃 & 버튼 비활성화 구현 완료
  public/data/data.json
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 완료

#11 [40기 김채영]Modify: branch name 변경 / conflict 해결 완료
  package-lock.json
  package.json
  public/images/loupe.png
  public/images/menu.png
  public/images/shopping-cart.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
  src/styles/mixins/flex.scss
Labels: 멘토 리뷰 요청

#10 [40기 윤수인] Refactor : 회원가입- 멘토 리뷰 반영 & conflict 해결
  public/images/check.png
  public/images/checked.png
  src/Router.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 완료

#14 [40기 윤수인] Refactor : 로그인- 멘토 리뷰 반영 & conflict 해결
  src/api/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 완료

#15 [40기 김채영]Fix: conflict 해결 완료
  .stylelintrc.js
  public/data/categoryList.json
  public/images/WESELY-logo.png
  public/images/magnify.png
  public/images/pill.png
  public/images/razor.png
  public/images/water.png
  src/Router.js
  src/components/CategoryList/CategoryList.js
  src/components/CategoryList/CategoryList.scss
  src/components/CategoryList/categoryInfoList.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/styles/variables.scss
Labels: 완료

#12 [40기 김나희]Add : 상세 상품 페이지 레이아웃 구현
  public/data/MOCK_DATA.json
  public/images/MCimage1.png
  public/images/MCimage2.jpg
  public/images/MCimage3.jpg
  public/images/MCimage4.jpg
  public/images/productInfo.png
  src/components/Nav/Nav.scss
  src/pages/ProductDetail/MenuTab.js
  src/pages/ProductDetail/MenuTab.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/MainPage/MainCarousel.js
  src/pages/ProductList/MainPage/MainPage.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#16 [40기 윤수인] ADD : 회원가입 추가 기능 구현 (주소 입력칸 추가)
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#13 [40기 신창훈] FIxed: ProductList Backend 충돌해결
  public/data/MOCK_DATA1.json
  public/data/MOCK_DATA2.json
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  public/images/maskimage.png
  src/Router.js
  src/pages/Footer/Footer.js
  src/pages/ProductList/Product/CategoryList.js
  src/pages/ProductList/Product/CategoryList.scss
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/Product/ProductCard.js
  src/pages/ProductList/Product/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.js
Labels: 완료

#18 [40기 김나희] Modify: 제품 캐러셀 서버 이미지로 변경 및 productcard 컴포넌트 활용
  .stylelintrc.js
  src/Router.js
  src/api/config.js
  src/pages/MainPage/MainCarousel.js
  src/pages/MainPage/MainCarousel.scss
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainProductCard.js
  src/pages/MainPage/MainProductCard.scss
  src/pages/MainPage/ProductCarousel.js
  src/pages/MainPage/ProductCarousel.scss
  src/pages/ProductList/MainPage/ProductCarousel.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#17 [40기 김나희]ADD: 제품 상세 페이지 장바구니 모달창 및 장바구니 담기 기능 구현
  public/images/MCimage2.png
  public/images/MCimage3.png
  public/images/MCimage4.png
  src/Router.js
  src/api/config.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Nav/Nav.scss
  src/pages/Login/Login.scss
  src/pages/ProductDetail/MenuTab.js
  src/pages/ProductDetail/MenuTab.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#21 [40기 김나희] 제품 카드 장바구니 담기 기능 구현 및 모달포탈 이용
  public/index.html
  src/api/config.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/ScrollUpTop/ScrollUpTop.js
  src/components/ScrollUpTop/ScrollUpTop.scss
  src/pages/MainPage/MainProductCard.js
  src/pages/MainPage/ProductCarousel.js
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#19 fix: 최종 ProductList conflict 해결
  public/data/MOCK_DATA1.json
  public/data/MOCK_DATA2.json
  public/data/all1.json
  public/data/category1.json
  public/data/category2.json
  public/data/category3.json
  public/data/categoryList.json
  public/data/subCategory1.json
  public/data/subCategory10.json
  public/data/subCategory11.json
  public/data/subCategory2.json
  public/data/subCategory3.json
  public/data/subCategory4.json
  public/data/subCategory5.json
  public/data/subCategory6.json
  public/data/subCategory7.json
  public/data/subCategory8.json
  public/data/subCategory9.json
  public/images/1.jpeg
  public/images/2.jpeg
  public/images/3.jpeg
  public/images/4.jpeg
  public/images/ad1.jpeg
  public/images/ad2.jpeg
  public/images/ad3.jpeg
  public/images/ad4.jpeg
  src/Router.js
  src/components/CategoryList/CategoryList.js
  src/pages/ProductList/Product/CategoryList.scss
  src/pages/ProductList/Product/ProductCard.js
  src/pages/ProductList/Product/ProductCard.scss
  src/pages/ProductList/Product/SubCategoryList.js
  src/pages/ProductList/Product/SubCategoryList.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.js
Labels: 완료

#22 [40기 김나희 ]Add: nav 장바구니 버튼 로그인 유효성 검사 추가
  public/data/MOCK_DATA.json
  public/data/category1.json
  public/data/category2.json
  public/data/category3.json
  public/data/categoryList.json
  public/data/subCategory1.json
  public/data/subCategory10.json
  public/data/subCategory11.json
  public/data/subCategory2.json
  public/data/subCategory3.json
  public/data/subCategory4.json
  public/data/subCategory5.json
  public/data/subCategory6.json
  public/data/subCategory7.json
  public/data/subCategory8.json
  public/data/subCategory9.json
  src/api/config.js
  src/components/Nav/Nav.js
  src/pages/Cart/Cart.js
  src/pages/Cart/components/CartItem.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/MainPage/MainProductCard.js
  src/pages/MainPage/MainProductCard.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Product/ProductCard.js
  src/pages/ProductList/ProductList.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청
